import os
import json
from pathlib import Path
from langchain_community.embeddings import OpenAIEmbeddings
from langchain_community.vectorstores.pgvector import PGVector
from langchain_core.documents import Document

# PGVector config
CONNECTION_STRING = "postgresql://postgres:postgres@postgres:5432/vectors"
COLLECTION_NAME = "documents"

# Load from local JSONL file (generated by generate-attack-docs.py)
DATA_PATH = Path(__file__).parent / "data" / "generated_docs" / "maul.jsonl"

# Convert to LangChain Documents
documents = []

with open(DATA_PATH, "r", encoding="utf-8") as f:
    for line in f:
        row = json.loads(line.strip())
        content = row.get("content", "").strip()
        if content:
            metadata = row.get("metadata", {})
            metadata["source"] = "maul"
            metadata["id"] = row.get("id")
            documents.append(Document(
                page_content=content,
                metadata=metadata
            ))

print(f"Loaded {len(documents)} documents from {DATA_PATH}.")

# Embed and store
embeddings = OpenAIEmbeddings()
db = PGVector.from_documents(
    documents,
    embedding=embeddings,
    collection_name=COLLECTION_NAME,
    connection_string=CONNECTION_STRING,
)

print(f"Ingested {len(documents)} documents into pgvector.")
